FROM python:3.8

WORKDIR /worker

COPY ./requirements.txt /worker/requirements.txt

RUN pip install -r requirements.txt

COPY ./model_worker.py /worker/model_worker.py
COPY ./model/model.py /worker/model.py

EXPOSE 8000

CMD python /worker/model_worker.py
